evaluate_freq: 5  # Evaluation frequency
save_as: False # What to save the model as, if False, then it is saved as the wandb run name
verbose: 1  # 0: silent, 1: progress bar, 2: one line per epoch
device: "cuda"  # Options: "cuda", "mps", "cpu"
validation_size: 0.2  # Fraction of the training set to use as validation
dataloader_num_workers: 8
seed: 42
load_best_model: True # If loading a model, load the best model. If False, load the last model.
save_many_accs: False
early_stopping_accuracy_thresholds: [0.9, 0.91, 0.92, 0.93, 0.94] # Threshold for saving separate models with different accuracies. 
                                                                  # If the model reaches one of these accuracies, it will be saved as "model_acc_{accuracy}.pt". 
                                                                  # This is useful for evaluating the attack success rate at different target model accuracies.
                                                                  # Use with AT-AT to get model with high accuracy and high PGD attack success rate.

wandb:
  track: True
  project: "ProjectName" # where current run will be loaded
  entity: "EntityName" # where current run will be loaded
  project_to_load_from: "ProjectName" # which project a loaded run will be loaded from in wandb
  run_id: False # set a current wandb run id
  run_name: False
